### ISSUE TITLE
Not support the latest version of swift using carthage

### ISSUE THREAD

**Issue by qiushuitian** [devxoul/URLNavigator#95]
run the command 
```
carthage update --platform iOS
```
it shows:

```
"Incompatible Swift version - framework was built with 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2) and the local version is 4.1 (swiftlang-902.0.48 clang-902.0.37.1)."
```

**Comment by tdharmon** [comment]
I'm also facing this issue. @devxoul any guess when this will be updated?

**Comment by lpardoiph** [comment]
I had to update my project Swift version to 4.1 and it doesn't compile any more. @devxoul any news when this will be updated?

**Comment by devxoul** [comment]
Hey folks, I updated the prebuilt binary of 2.0.4 release. Could you please try again with it?

**Comment by lpardoiph** [comment]
Hey @devxoul, I'm having the same problem again after updating to xcode 9.4 and swift 4.1.2.

`*** Downloading URLNavigator.framework binary at "2.0.5"`
`*** Skipped installing URLNavigator.framework binary due to the error:`
`	"Incompatible Swift version - framework was built with 4.1 (swiftlang-902.0.48 clang-902.0.37.1) and the local version is 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)."`

**Comment by devxoul** [comment]
I released 2.0.6 which support  4.1.2 (swiftlang-902.0.54 clang-902.0.39.2).

**Comment by lpardoiph** [comment]
Thanks! It's working great again.

**Comment by devxoul** [comment]
Please re-open this issue if you still have a problem :)

**Comment by prattprattpratt** [comment]
@devxoul I'm getting this same issue with Swift 4.2
